### ISSUE TITLE
300+ permissions

### ISSUE THREAD

**Issue by jaychapani** [jasontaylordev/flexible-aspnetcore-authorization#7]
How do you think we could handle a scenario considering 300+ permissions where this approach limits us to 64 max permissions?

**Comment by jasontaylordev** [comment]
> How do you think we could handle a scenario considering 300+ permissions where this approach limits us to 64 max permissions?

I'd suggest creating multiple levels of permissions to create a structure over such a large number of items. For example: Customers / Create, Modify, View. This will make it easier for administrators to find and assign permissions.

Don't use enumerations to store the permissions. There are many other approaches. For example, use C# constants inside static classes possibly backed by database storage.

**Comment by jaychapani** [comment]
Thank you for the suggestion. We have a hierarchy of permissions. We tried this in the past, keeping all permissions in the cookie/token but it increases the size of the cookie/token. Do you have any suggestion for logic similar to bitwise and/or operators with enums that help to keep the cookie/token size smaller?

**Comment by jasontaylordev** [comment]
What if you store the permissions in the database and use the primary key in the token?

**Comment by jaychapani** [comment]
We are storing the permissions in the DB. Are you suggesting to keep a list of permissions primary keys in the token?

**Comment by jasontaylordev** [comment]
> We are storing the permissions in the DB. Are you suggesting to keep a list of permissions primary keys in the token?

Yes, as claims; [1, 2, 6, 23, 57].

**Comment by jaychapani** [comment]
That works but I have to think of managing dynamic enum, dictionary, or constant to match the permission key that can be used in the application in a readable way like an enum. Any suggestion on this would be appreciated.

**Comment by jasontaylordev** [comment]
> That works but I have to think of managing dynamic enum, dictionary, or constant to match the permission key that can be used in the application in a readable way like an enum. Any suggestion on this would be appreciated.

Managing as in? I'd just use an enum without Flags. The important part is strongly-typed permissions.

**Comment by leeleito** [comment]
Hey @jaychapani  did you get this working? Have similar problem. At the moment we have the Permissions as long which is ok but the list and maintenance is getting harder. It would be greate to somehow store a Manage permission and then the crud operations to go with it. Instead of CreateProject,Readproject.. have ManageProjects with a separate Create+Read

Did you end up stroing the permissionId in the claims?

This works, but long list!

[Flags]
public enum Permissions: long
{
}

**Comment by PeterSchlicker** [comment]
@leeleito: just have a look to: 
https://github.com/alirezanet/InfiniteEnumFlags

**Comment by leeleito** [comment]
Thanks @PeterSchlicker will take a look. I think I will have similar issue though in that maintaining hundreds of permissions is quite diffcilut using a single enum. I believe that is what jason is saying above to break it up into several enums?
